### ISSUE TITLE
Generate Rails 7 application 

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/imagecat-rails#8]
### Acceptance criteria

- [x] Use asdf to specify software versions 
- [x] Use ruby 3.2 
- [x] Use rails 7
- [x] Specify postgresql when you generate the application 
- [x] Update README on how to start the application locally 
- [x] The rails application is in github

**Comment by maxkadel** [comment]
Once you have the rails gem installed, you can type `rails new --help` to see options. Ones to pay particular attention to include:
- `--database=postgresql`
- `--skip-test` (this is because we will be using rspec rather than the builtin test framework)
- You may want to look at the `--javascript` option - the default is importmap. I think our other applications are using Vite, but that is not an option to start the application with. 
- You may also want to look at the `--css` option - I think our other projects use bootstrap, but I don't know whether they're set up the same way as `rails new` with that flag does it.

@sandbergja might have better ideas about the javascript and css options, and @bess might suggest that you skip some of these flags altogether.
